### ISSUE TITLE
Update the civic.json read me

### ISSUE THREAD

**Issue by noneck** [BetaNYC/betanyc-projects-list#22]
Subtasks:
* update readme to be “done”
* Add more to needs example: Designer, developer, data scientist, subject matter experts, project manager, community testing, deployment support

**Comment by bcarancibia** [comment]
This issue needs to be migrated to the correct repo.

**Comment by noneck** [comment]
I've moved it over to https://github.com/BetaNYC/civic.json/issues/16 

Note there are many civic.json tickets. Y'all should work with @ameensol to close them down.
