### ISSUE TITLE
Replace <Apple/> Logo with attached BetaNYC logo.

### ISSUE THREAD

**Issue by noneck** [BetaNYC/betanyc-projects-list#26]
Replace the <apple/> logo with the BetaNYC B.

https://github.com/BetaNYC/What-is-BetaNYC/blob/master/BetaNYC%20Logos/BetaNYC_short_blue_on_white.png

![betanyc_short_blue_on_transparent](https://cloud.githubusercontent.com/assets/94735/6129864/4562ab74-b10f-11e4-83bf-2cc54a1e102c.png)

**Comment by seanluciotolentino** [comment]
Can this be added to the beta.nyc/images folder? Right now it's being hosted from github was is probably less than ideal.
