### ISSUE TITLE
Update home page text 

### ISSUE THREAD

**Issue by noneck** [BetaNYC/betanyc-projects-list#27]
Replace the introduction test to the following.

>This is a collection of tools and projects being developed by NYC's civic tech community. If you have questions about civic tech, join us at [talk.beta.nyc](https://talk.beta.nyc).

> Are you working on a civic tech project & want it listed here? Add a [civic.json](https://github.com/BetaNYC/civic.json) file to your project and file a [github issue](https://github.com/BetaNYC/betanyc-projects-list/issues/new) with your project's Github URL.

**Comment by bcarancibia** [comment]
Done. Was not sure if you the top part of the original text needed to be removed. Also, removed the break because it looked bad. Will replace civic.json file creator when civic.json form built.
