### ISSUE TITLE
Citygram.nyc

### ISSUE THREAD

**Issue by dirkkelly** [BetaNYC/betanyc-projects-list#32]
https://www.citygram.nyc/civic.json

**Comment by seanluciotolentino** [comment]
thanks @dirkkelly -- can you send the link to the github repo? I think it is [this one] (https://github.com/codeforamerica/citygram) but I wasn't sure

**Comment by dirkkelly** [comment]
@seanluciotolentino https://github.com/BetaNYC/citygram-nyc/blob/master/public/civic.json please let me know if this file should be in the root of the project as opposed to the root of the web application.

**Comment by seanluciotolentino** [comment]
@dirkkelly  Indeed put the civic.json in the root folder.

**Comment by dirkkelly** [comment]
@seanluciotolentino sorted :) https://github.com/BetaNYC/citygram-nyc/blob/master/civic.json

**Comment by dirkkelly** [comment]
How do we fix contributors etc?

![screen shot 2015-02-24 at 12 00 39 am](https://cloud.githubusercontent.com/assets/81055/6343549/36bccbfa-bbb8-11e4-9074-01b801faa732.png)
