### ISSUE TITLE
Mapping unplanned MTA service alerts

### ISSUE THREAD

**Issue by daniellecarrick** [BetaNYC/betanyc-projects-list#34]
We are scraping real time MTA alert data and capturing it in a database to visualize frequency, duration and time of different alert types (sick passenger, rail condition, police activity, etc.) on an interactive map.

https://github.com/MTA-Service-Alerts-beta-nyc/service-alerts

**Comment by daniellecarrick** [comment]
Collaborators
Ray Chu, Henry Baughman, Malena Rubino, Danielle Carrick, Sean Adams, Bethany Beech

Award Considerations
Best Map
Best Data Visualization
Best Scraper Team

**Comment by reihned** [comment]
@seanluciotolentino Hi, can you update us?

```
Collaborators
Raymond Chiu, Henry Baughman, Malena Rubino, Danielle Carrick, Sean Adams, Bethany Beech, Rebecca Ackerman
```

**Comment by seanluciotolentino** [comment]
Your project has been added -- check it out on the [projects page] (projects.beta.nyc)!
