### ISSUE TITLE
Homeward

### ISSUE THREAD

**Issue by Maelstroms38** [BetaNYC/betanyc-projects-list#37]
Homeward shows a map of homeless shelters in NYC.

Team Partners - Matt, Faigy Mayer, and Joe Eastman.
https://github.com/Maelstroms38/Homeward
![ios simulator screen shot feb 21 2015 5 54 22 pm](https://cloud.githubusercontent.com/assets/7039196/6316403/bd41f424-b9f2-11e4-8e9a-8fca0be2be1d.png)

**Comment by faigym** [comment]
We are applying for Best Civic Hack / Best of Show
Best User Experience
Most Creative Use of Data
