### ISSUE TITLE
nyc rent stabilization unit counts scrapers

### ISSUE THREAD

**Issue by talos** [BetaNYC/betanyc-projects-list#38]
__Project name:__ nyc stabilization unit counts scrapers
__URL:__ https://github.com/talos/nyc-stabilization-unit-counts
__Description:__ Liberate NYC DOF tax documents to a machine readable format.  Extract estimated earnings/expenses & unit counts for stabilized buildings.
__Awards Applications__: Best Civic Hack / Best of Show, Best Scraper Team, Most Creative Use of Data
__Partners__: @talos @clhenrick @akilism @aepyornis @romeboards

**Comment by seanluciotolentino** [comment]
Added! Thanks
