### ISSUE TITLE
Map overlaying NYC public school enrollment/student age/DOT injury&fatality Vision Zero data

### ISSUE THREAD

**Issue by jooltman** [BetaNYC/betanyc-projects-list#39]
This would help prioritize future DOT pedestrian safety design improvements for most dangerous areas with most vulnerable students, and hopefully motivate DOE to become more involved with student safety on streets.  Lucian (sp?) has graciously offered to map this!

**Comment by seanluciotolentino** [comment]
The map is going to be add to the (WalkSafer project) [https://github.com/seanluciotolentino/dangerous-intersections]. --Lucio

**Comment by jooltman** [comment]
Thanks, Lucio!  Looking forward to seeing it.
