### ISSUE TITLE
NYPD Data Comparison CompStat vs. Dangeous Moving Violation Enforcement

### ISSUE THREAD

**Issue by jooltman** [BetaNYC/betanyc-projects-list#41]
Hoping to take Tim's scraped CompStat info by precinct for last year, compile it into monthly figures, and compare those numbers to monthly TrafficStat numbers for dangerous moving violations.  The top three we could focus on are Failure to Yield, Speeding, and Red Light. Vision Zero initiative started last January I believe, so that would be a good start date.

It would be a powerful advocacy tool to be able to show data and ask for more Vision Zero enforcement in precincts that have low numbers in both datasets.

I am trying to counter the "we don't have enough manpower to focus on streets" argument.

Would also be useful to get ahold of individual precinct staffing levels, but does anyone know if this is available?  Don't see it on Open Data portal...

Hung Dinh from Place Pixel is going to work on this with me tomorrow.

**Comment by hdinh** [comment]
Github project page:
https://github.com/NYPDVisionZeroAccountability

Team Members:
Joanna Smith
Brandyn Friedly
Coati Tlahcomiztli
Carol Crump
Hung Dinh

**Comment by seanluciotolentino** [comment]
Added! Thanks
