### ISSUE TITLE
City Record civic.json

### ISSUE THREAD

**Issue by jqnatividad** [BetaNYC/betanyc-projects-list#44]
{
    "status": "Beta",
    "thumbnailUrl": "http://assets.nydailynews.com/polopoly_fs/1.1683036!img/httpImage/city-record-jpg.jpg",
     "bornAt": "City Hall",
    "geography": "NYC",
    "politicalEntity":"NYC City Council",
    "type":"Dataset",
    "needs": [
        {"need": "NLP experts"},
        {"need": "Python Devs"},
        {"need": "Data Wranglers"},
    ],
    "categories": [
        {"category": "Finance"},
        {"category": "Procurement"},
       {"category": "Open Data"},
       {"category": "Human Resources"},
    ]
}

**Comment by seanluciotolentino** [comment]
@jqnatividad -- is this a project submission? We do have the city record project...

**Comment by noneck** [comment]
Yes. It is known as the CityRecord Online project < https://github.com/CityOfNewYork/CROL-PDF >
