### ISSUE TITLE
Shapefiles for all MTA bus routes.

### ISSUE THREAD

**Issue by kuanb** [BetaNYC/betanyc-projects-list#56]
oba-path-extractor (https://github.com/Bus-Data-NYC/oba-path-extractor) is a simple Node tool to extract all metadata provisioned from the MTA used on their Bustime application with regards to target bus lines. Within oba-path-extractor is the resulting file `geojsons/` which contains a clean GeoJSON FeatureCollection shapefile for both inbound and outbound routes on every bus line in the MTA system.

**Comment by kuanb** [comment]
Improvements are being added now that include rolling in stops locations as well as calculating exact points along route where stops exist and adding in a point in shapefile marked as such.

**Comment by seanluciotolentino** [comment]
Your project has been added to the projects page :)
